### ISSUE TITLE
Suggestion: Add email field in Readme

### ISSUE THREAD

**Issue by c990802** [customerio/customerio-node#10]
As subject states, this is about email sending. Would be great to indicate how to pass the email to cio, and not leave it to our guessing :)
thanks

**Comment by joepurdy** [comment]
We've updated the README examples to show adding emails addresses as data attributes. The [examples/ directory](https://github.com/customerio/customerio-node/tree/master/examples) also includes a number of examples to make it clear how to integrate with Customer.io using the Node.js library.
