### ISSUE TITLE
Reading package.json doesn't work when bundled

### ISSUE THREAD

**Issue by hansottowirtz** [customerio/customerio-node#100]
We're bundling our backend with Rollup before uploading to Lambda, and this line of code inside `lib/request.ts` just made our Lambda hang, because of some infinite loop caused by Rollup + this particular piece of code. It happens when it can't find a `package.json` (and because everything is bundled, there is no `package.json` uploaded to AWS Lambda.)

```ts
const PACKAGE_JSON = findPackageJson(resolve(__dirname, '..'));
```

Could this be turned into something that also works inside bundled files?
e.g.:

```ts
let PACKAGE_JSON: any;
try {
  PACKAGE_JSON = require('../package.json');
} catch (e) {}
```

**Comment by codinronan** [comment]
We actually ran into this as well, this would be a huge help. It's only read to get the version value inside package.json, this seems like the kind of thing that could be provided as a config value so the developer is free to use whatever method appropriate to provide it.

**Comment by mike-engel** [comment]
Hi @codinronan and @hansottowirtz. Thanks for your patience on this—I think we have a solution available (#105) as a beta release: `3.2.1-beta.0`. If you could try this out and let me know if it works for you, then we can merge and publish it for you. Thanks!

```sh
npm i customerio-node@3.2.1-beta.0
```

**Comment by cmdmescall** [comment]
Not either of the other posters but came across this because we found we were having similar issues when bundling for lambda deployment - timing out/hanging for the same reason - and can confirm that after upgrading to the beta 3.2.1-beta.0 package and testing it the problem has gone and we can deploy/run as we'd expect. Thanks @mike-engel

**Comment by mike-engel** [comment]
Thanks for testing out the beta release @cmdmescall! I'll try and cut a new release after #106 is merged.
