### ISSUE TITLE
Incrementing the value of an attribute

### ISSUE THREAD

**Issue by georgeben** [customerio/customerio-node#116]
Great work on the library. How do I increment the value of a property on a person? For example:
```js
cio.identify(1, {
  email: 'customer@example.com',
  created_at: 1361205308,
  first_name: 'Bob',
  plan: 'basic',
  number_of_purchases: 0
});
```

Each time a user makes a purchase, I want to increment `number_of_purchases` by 1, so I don't have to write a database query to count all the purchases a user has made. Thank you.

cc: @mike-engel

**Comment by mike-engel** [comment]
Hi @georgeben! Our APIs (regardless of language) don't have a way to increment a specific attribute of a profile. If you need to update an attribute, you need to make another `identify` call with the updated attribute value. 

```js
cio.identify(1, {
  email: 'customer@example.com',
  number_of_purchases: 1
});
```
