### ISSUE TITLE
All support for keep alive connections

### ISSUE THREAD

**Issue by adityapatadia** [customerio/customerio-node#119]

**Comment by mike-engel** [comment]
@adityapatadia can you provide more information on this? What exactly are you looking to see added for this?

**Comment by mike-engel** [comment]
Thanks @adityapatadia. I believe this is doable already today. The Track and API clients allow you to pass an object for defaults that get passed into the request handler. You could pass in your own agent there that uses node's `keepAlive` option, like so:

```javascript
const { Agent } = require('http');
const { APIClient, RegionUS, RegionEU } = require('customerio-node');

const keepAliveAgent = new Agent({
  keepAlive: true,
  keepAliveMsecs: 5000,
});
const cio = new APIClient('siteId', 'apiKey', { region: RegionUS, agent: keepAliveAgent });
```
