### ISSUE TITLE
"400 Bad Request" when using new "getCustomersByEmail" method with valid email addresses

### ISSUE THREAD

**Issue by jordanhailey** [customerio/customerio-node#131]
See: https://github.com/customerio/customerio-node/pull/124

When calling `getCustomersByEmail("example@email.com")` the query parameters are not being passed along. So, as a result, the GET request URL is `/v1/customers` instead of `/v1/customers?email=example@email.com`.

**Comment by jordanhailey** [comment]
Absolutely no rush. 

For anyone needing this immediately, forking the main repo, transpiling from TS to JS with `tsc`, and updating your references to the forked library is always an option. Closing this issue.


Thanks! 😊

**Comment by PiotrPawelski** [comment]
Hi @mike-engel , do you have any ETA of this change?

**Comment by mike-engel** [comment]
I'm still waiting on #130. I'll give them another day to update their PR, otherwise I'll make a new deploy. Thanks for the patience!

**Comment by mike-engel** [comment]
Thanks for the patient everyone. This was released with `3.5.0`
