### ISSUE TITLE
API docs detail missing

### ISSUE THREAD

**Issue by DrChrispoper** [customerio/customerio-node#133]
Hi, not sure where is the best place to post this.

There is an important detail missing from the transactional messages docs for one parameter.
https://customer.io/docs/api/#operation/sendEmail

`send_at`
A unix timestamp determining when the message will be sent. The timestamp can be up to 90 days in the future. If this value is in the past your message is sent immediately.

The timestamp should be in **seconds**! 
Not **milliseconds** (which `new Date().getTime()` or `Date.now()` returns)

**Comment by mike-engel** [comment]
Thanks @DrChrispoper, I spoke to our documentation team and they're going to add a note in the docs soon to specify that it's seconds, not ms
