### ISSUE TITLE
json TS2345: Argument of type 'null' is not assignable to parameter of type 'Record<string, any> | PromiseLike<Record<string, any>>'

### ISSUE THREAD

**Issue by laser-bemlo** [customerio/customerio-node#143]
I am getting the following error, while trying to use the package:

```
error TS2345: Argument of type 'null' is not assignable to parameter of type 'Record<string, any> | PromiseLike<Record<string, any>>'
```

It happens when the project is compiled as part of NestJs applciation.
Basically, it says that `json` has a wrong type, which was deducted from value assigned to it (an it is only `null`). While function response never expects `null` as return type.

<img width="1201" alt="image" src="https://github.com/customerio/customerio-node/assets/113097800/cc4109ea-6ae0-4229-90cd-61a083149863">

![image](https://github.com/customerio/customerio-node/assets/113097800/582de09d-cfb7-4037-8da6-809581f345ca)

Can you modify it to something like: `resolve(json ?? {});`?

**Comment by clabland** [comment]
Thanks for writing up this issue, we have a change here which should hopefully solve it: https://github.com/customerio/customerio-node/pull/144

**Comment by clabland** [comment]
Thanks again for the report, this should be resolved in https://github.com/customerio/customerio-node/releases/tag/v4.1.1.
