### ISSUE TITLE
Clarify how to send base64 encoded attachemnts

### ISSUE THREAD

**Issue by Sealos** [customerio/customerio-node#147]
I am writing to request documentation or guidance on how to properly send Base64 attachments via email. I am encountering difficulties when attempting to include Base64-encoded attachments in the Transactional API.

The web documentation specifies that is possible (https://customer.io/docs/journeys/email-attachments/), but it's not clear how to do it from this library.

**Comment by mike-engel** [comment]
Hi @Sealos, could you provide an example of how you're currently trying to add an attachment and having trouble?
