### ISSUE TITLE
Destroying a User by Email Address instead of cio_id

### ISSUE THREAD

**Issue by mahirpiy** [customerio/customerio-node#151]
Is there a way to use the `destroy()` method by passing in an email address instead of their `cio_id`?

**Comment by Tunechi28** [comment]
hello @mahirpiy, You can pass in the email address, cio_id or customerId to the destroy() method. tha API actually supports it.

cc @mike-engel

**Comment by mike-engel** [comment]
@Tunechi28 is correct: the `destroy` method calls the [delete customer](https://customer.io/docs/api/track/#operation/delete) endpoint, which supports `id` or `email` (whichever is an identifier) and `cio_id`
