### ISSUE TITLE
Unhandled Runtime Error. TypeError: url_1.URL is not a constructor

### ISSUE THREAD

**Issue by JimmyAG** [customerio/customerio-node#156]
I was trying to use `customerio-node` to get customer info in a Next 14 project, but when calling `.getCustomersByEmail` method of the client class I always end up with the same error: 

Here is the code: 

``` js

import { APIClient } from 'customerio-node'

export const CustomerIoClient = (function () {
  let client: APIClient | null = null

  function createClient(): APIClient {
    return new APIClient(process.env.CUSTOMERIO_APP_KEY || '')
  }

  return {
    getInstance: function () {
      if (!client) {
        client = createClient()
      }

      return client
    },
  }
})()

export const getCustomerByEmail = async (email: string) => {
  const cio = CustomerIoClient.getInstance()

  const res = await cio.getCustomersByEmail(email)

  return res
}
```

Windows: 10 /11 
Npm: 10.4.0
NodeJS: 18.18.0
NextJS: 14

**Comment by mike-engel** [comment]
Hi @JimmyAG, this issue is hard to debug unless you share the error with us. Can you please paste the error you’re receiving?

**Comment by JimmyAG** [comment]
> Hi @JimmyAG, this issue is hard to debug unless you share the error with us. Can you please paste the error you’re receiving?

Thanks for replying, @mike-engel 

It is really not much there, I'm calling the function inside the `onClick` of a Button. 
![image](https://github.com/customerio/customerio-node/assets/38320882/1f07b8de-1a3b-4a68-8424-1971f15cc8ac)

This is the component, I was testing if it is working or not before using it in another page:

```js
  const handleClick = async () => {
    const email = 'XXXXXX'

    const res = await getCustomerByEmail(email)
    console.log(res)
  }
```

**Comment by JimmyAG** [comment]
It is this line from the suggested file in the nodemodules file shown in the error:
```js
let url = new url_1.URL(uri);
```

but it is the node url, so I don't know what exactly is the issue:

This is from the same file in `customerio-node/dist/lib/request.js` 
```js
const url_1 = require("url");
```

**Comment by Chamed** [comment]
any updates on this?

**Comment by JimmyAG** [comment]
> any updates on this?

Not yet!

**Comment by mike-engel** [comment]
@JimmyAG this library is only meant to be used on the server, not on the client in a front end application. For use on the front end, the [JavaScript API](https://customer.io/docs/cdp/sources/connections/javascript/js-source/) should be used instead.
