### ISSUE TITLE
Feature: remove contacts in bulk

### ISSUE THREAD

**Issue by sshanzel** [customerio/customerio-node#161]
Hi, team. Good day. I've been scouring the docs page, but I can't seem to find an API to allow us to **remove contacts in bulk**. If it is available, can someone help us be pointed in the right direction?

If not, do you have any suggestions on how to do it for multiple records at the same time? I see the API only accepts one customer per call for the removal.

**Comment by mike-engel** [comment]
Hi @sshanzel. We have the [bulk track endpoint](https://docs.customer.io/api/track/#operation/entity) in the track v2 api that would allow you to delete multiple customers at once. As mentioned in https://github.com/customerio/customerio-node/issues/136, however, that API isn't part of this library yet, so you'll need to manually create the request in your app code.
