### ISSUE TITLE
Display the real error message instead of "Unknown error"

### ISSUE THREAD

**Issue by LaureRC** [customerio/customerio-node#29]
When calling the `identify` method (I'm using the last version "0.7.0" of your lib), and in the case where a 400 error happened because of a too long attribute value, here is what I get : 
```
message: 'Unknown error',
statusCode: 400,
...
body: '{\n' +
      '  "meta": {\n' +
      '    "errors": [\n' +
      `      "value for attribute 'myAttribute' cannot be longer than 1000 bytes"\n` +
      '    ]\n' +
      '  }\n' +
      '}\n',
```

After a look into your code, I noticed that this specific line : https://github.com/customerio/customerio-node/blob/52e27c2ff86a7b834621991b0fde9565ac5d5cac/lib/request.js#L48 suggests that the body should actually be formatted like this : 
```
meta {
    error // string
}
```

Whereas I'm getting this : 
```
meta {
    errors // array of string
}
```

Is it something that you are planning to deal with at some point ? For now, I handled it myself but it would be nice to include it in the lib I guess :)

**Comment by mike-engel** [comment]
Hi @LaureRC! Many apologies for letting this sit around for over a year, but with #59 and version `3.0.0` this should no longer be a problem 😄
