### ISSUE TITLE
Remove dependency on package: request

### ISSUE THREAD

**Issue by trmpowell** [customerio/customerio-node#59]
npm package "[request](https://www.npmjs.com/package/request)" has been deprecated and contains references to a [vulnerable version of ajv](https://snyk.io/vuln/SNYK-JS-AJV-584908). Removal of this package will remove this vulnerability within customerio-node package.

**Comment by mike-engel** [comment]
Hi @trmpowell! Thanks for filing this—you're absolutely right that we should remove our dependency on `request`, and that's something we're going to try and tackle by the end of next week.

In the meantime, this particular vulnerability/CVE is for a [regular expression DoS for `data` urls specifically](https://github.com/sindresorhus/normalize-url/commit/b1fdb5120b6d27a88400d8800e67ff5a22bd2103), so I don't believe there is any immediate risk by using `customerio-node` right now. That being said, we'll remove the dependency as soon as we can!

**Comment by mike-engel** [comment]
Thanks for your patience with this. As of #62 and version `3.0.0` the `request` dependency has been removed.
