### ISSUE TITLE
Cannot resolve https in customerio/node/dist/lib

### ISSUE THREAD

**Issue by ShuvoHabib** [customerio/customerio-node#68]
<img width="462" alt="Screenshot 2021-07-09 at 5 06 28 PM" src="https://user-images.githubusercontent.com/7802528/125079166-1fc3f280-e0e5-11eb-9554-9dd85461c26f.png">

<img width="366" alt="Screenshot 2021-07-09 at 6 39 29 PM" src="https://user-images.githubusercontent.com/7802528/125079207-2a7e8780-e0e5-11eb-9bd5-171537ce7f6a.png">

**Comment by swastik** [comment]
Hey @ShuvoHabib, which version of the package are you seeing this error on?

**Comment by mike-engel** [comment]
Additionally, what version of node you're using. `https` is a built-in node module that's part of the standard library. It looks like you're using webpack to use this project, so I'd be interested in your use case as well.

**Comment by ShuvoHabib** [comment]
Hi @swastik  @mike-engel Thank you for your quick response. We're trying to fix this issue using something different
