### ISSUE TITLE
Unhandled 'Unauthorized request' error

### ISSUE THREAD

**Issue by DrChrispoper** [customerio/customerio-node#71]
I am using version 3.0.1 
When using customer-io in development we don't pass a correct key.
So the calls return an `Unauthorized request`
But `request.js` tries to parse the string like this `JSON.parse(body)` and throws this error:
```
(node:34878) UnhandledPromiseRejectionWarning: Error: Unable to parse JSON. Error: SyntaxError: Unexpected token U in JSON at position 0 
Body:
 Unauthorized request
    at IncomingMessage.<anonymous> (/xxx/node_modules/customerio-node/dist/lib/request.js:48:39)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by TrueWill** [comment]
I'm also seeing this.
> Error: Unable to parse JSON. Error: SyntaxError: Unexpected token U in JSON at position 0

**Comment by mike-engel** [comment]
Thanks for reporting this @DrChrispoper. Unfortunately it has always worked this way as far as I can tell. I'm reaching out to the team here to see if we can make the response from the customer.io server valid JSON, which is the root cause of the problem here.

**Comment by DrChrispoper** [comment]
Thanks for coming back to me.
Yes, if they can send back a valid JSON it would solve the issue.

**Comment by mike-engel** [comment]
@DrChrispoper @TrueWill Thanks for your patience. Upon further investigation, we discovered that a change earlier this year changed the format for the unauthorized response. That's been reverted, and now an instance of `CustomerIORequestError` will be thrown/rejected with the message `Unauthorized error`.
