### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by TrueWill** [customerio/customerio-node#72]
In the README, it has this sample code:

```js
let cio = new TrackClient(siteId, apiKey, { region: RegionUS }, [defaults]);
```
The `[defaults]` argument is incorrect; the signature is `(siteid: string, apikey: string, defaults?: Partial<TrackDefaults> | undefined)`.

This example is also incorrect in TypeScript:

```js
const cio = new TrackClient(123, 'abc', {
  timeout: 5000
});
```

`siteId` (123) should be a string.

**Comment by mike-engel** [comment]
Thanks for catching this @TrueWill! It's fixed now with #73
