### ISSUE TITLE
Transactional Mails with Umlauts

### ISSUE THREAD

**Issue by jaymaycry** [customerio/customerio-node#86]
I think it's an API issue but when I send special characters as message data it returns "Request entity must be JSON encoded and not exceed 2548 KB.". When I replace the special characters with &auml; everything works. Now have to write a helper function to parse the json object for those characters and replace them.

To reproduce:

```js
  const request = new SendEmailRequest({
    to: <your email>,
    transactional_message_id: <message id>,
    message_data: {
      name: "Stämpfli", // "St&auml;mpfli" works here..
    },
    identifiers: {
      id: <customer id>,
    },
  });

  const apiClient = new APIClient(<api key>);

  return apiClient.sendEmail(request);
```

**Comment by mike-engel** [comment]
Hey @jaymaycry! Thanks for the patience. I haven't been able to reproduce this, so I don't think it's an issue with `customerio-node`, and is more likely an issue with the API at some point.

Can you use the in-app "Contact support" functionality if you're still seeing this issue? That will allow us to debug your issue further with your account, message, etc. 

Thanks, and let me know if you have any trouble!
