### ISSUE TITLE
Error(400) When trying to set fake_bcc options on transaction API

### ISSUE THREAD

**Issue by prafful1234** [customerio/customerio-node#91]
Found this issue on transaction API where by default the value for fake_bcc is `true` and due to this, it leads to parent recipient's name + email is appended to the subject.

When trying to disable this option and following the error encountered with the library, whereas it works fine on the API side.

```
CustomerIORequestError: Request entity must be JSON encoded and not exceed 3024 KB.
```

`fake_bcc` should be a boolean as on the API and seem to be the cause of this issue, when types are overwritten and we pass a boolean value for `fake_bcc` things work fine on API as well as with CURL.

Please suggest if any additional updates would be required, adding an issue for tracking.

Will send a fix soon.

**Comment by mike-engel** [comment]
This should now be fixed in `3.1.1`. Thanks @prafful1234!
